algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print('Só tem espaços? ', algo.isspace())
print('É um numero? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanumérico? ', algo.isalpha())
print('Está em maiuscula? ',algo.isupper())
print('Está em minuscula? ',algo.islower())
print('Está capitalizada? ',algo.istitle())
